# -*- coding: utf-8 -*-
"""validacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I53rsaFUfOLdOFCWyREWdhmna3vzZQrJ
"""

def valide_int(pergunta):
  while True:
    try:
      n = int(input(f'{pergunta}'))
    except ValueError:
      print('Valor inválido! Digite um número inteiro')
    else:
      break
  return n

def valide_float(pergunta):
  while True:
    try:
      n = float(input(f'{pergunta}'))
    except ValueError:
      print('Valor inválido! Digite um número')
    else:
      break
  return n

def valide_num(pergunta):
  while True:
    try:
      n = float(input(f'{pergunta}'))
    except ValueError:
      print('Valor inválido! Digite um número')
    else:
      if n != 1 and n != 2 and n != 3 and n != 4:
        print('Valor inválido! Digite um número entre 1 a 4')
      else:
        break  
  return n