# -*- coding: utf-8 -*-
"""Dados_absolutos_relativos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTs0RpUzpLCutyUPKljSX5g24iOL_nPU

# Porcentagem
"""

import pandas as pd

dados = {'emprego': ['Adminstrador_banco_dados', 'Programador', 'Arquiteto_redes'],
         'nova_jersey': [97350, 82080, 112840],
         'florida': [77140, 71540, 62310]}

type(dados)

dados

dataset = pd.DataFrame(dados)
dataset

dataset['nova_jersey'].sum()

dataset['florida'].sum()

dataset['%_nova_jersey'] = (dataset['nova_jersey'] / dataset['nova_jersey'].sum()) * 100

dataset['%_florida'] = (dataset['florida'] / dataset['florida'].sum()) * 100

dataset

"""## Exercício percentuais"""

dataset = pd.read_csv('census.csv')

dataset.head()

dataset2 = dataset[['income', 'education']]
dataset2

dataset3 = dataset2.groupby(['education', 'income'])['education'].count()

dataset3

dataset3.index

dataset3[' Bachelors', ' <=50K'], dataset3[' Bachelors', ' >50K']

3134 + 2221

# % >50K
(2221 / 5355) * 100

# % <=50K
(3134 / 5355) * 100

"""## Exercício coeficientes e taxas"""

dados = {'Ano_Graduacao': ['1º', '2º', '3º', '4º', 'Total'],
         'Matriculas_Março': [70, 50, 47, 23, 190],
         'Matriculas_Novembro': [65, 48, 40, 22, 175]}

type(dados)

dataset = pd.DataFrame(dados)

dataset.shape

dataset.head()

dataset['Evasão'] = dataset['Matriculas_Março'] - dataset['Matriculas_Novembro']

dataset

dataset['Taxa de Evasão'] = (dataset['Evasão'] / dataset['Matriculas_Março']) * 100

dataset

