# -*- coding: utf-8 -*-
"""shell_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDou9pzIp2PZxj8plMHQjnsmI70bSm-o
"""

import numpy as np

def shell_sort(vetor):
  intervalo = len(vetor) // 2

  while intervalo > 0:
    for i in range(intervalo, len(vetor)):
      temp = vetor[i]
      j = i
      while j >= intervalo and vetor[j - intervalo] > temp:
        vetor[j] = vetor[j - intervalo] 
        j -= intervalo 
      vetor[j] = temp 
    intervalo //= 2
    
  return vetor

shell_sort(np.array([15, 34, 8, 3]))

shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

shell_sort(np.array([8,5,1,4,2,3]))